import { build } from 'vite';
import react from '@vitejs/plugin-react';
import { writeFile, readFile, mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd();
const output=process.argv.slice(2).find(arg=>!arg.startsWith('--')) || 'dist/index.html';
await mkdir('.sites-runtime',{recursive:true});
await writeFile('.sites-runtime/offline.tsx',`import React from 'react'; import {createRoot} from 'react-dom/client'; import Home from '../app/page'; import '../app/globals.css'; createRoot(document.getElementById('root')!).render(<Home/>);`);
await build({configFile:false, plugins:[react()], resolve:{alias:{'@':root}}, build:{outDir:'.sites-runtime/offline',emptyOutDir:true,lib:{entry:path.join(root,'.sites-runtime/offline.tsx'),name:'Pokerlabor',formats:['iife'],fileName:()=> 'app.js'},minify:true},define:{'process.env.NODE_ENV':'"production"'}});
const css=(await readdir('.sites-runtime/offline')).filter(x=>x.endsWith('.css'));
const style=(await Promise.all(css.map(x=>readFile('.sites-runtime/offline/'+x,'utf8')))).join('\n');
const js=await readFile('.sites-runtime/offline/app.js','utf8');
const html=`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pokerlabor</title><style>${style}</style></head><body><div id="root"></div><script>${js.replaceAll('</script','<\\/script')}</script></body></html>`;
const imageData = 'data:image/webp;base64,' + (await readFile('public/table.webp')).toString('base64');
await mkdir(path.dirname(output),{recursive:true});
await writeFile(output,html.replaceAll('/table.webp',imageData).replace(/[ \t]+(?=\r?$)/gm,'')); console.log('Offline app ready:',output);
